version: "3.7"
services:
  db:
    image: postgres:16
    container_name: db_app
    env_file:
      - ./.env
    command: -p 1221
    expose:
      - 1221

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370

  app:
    build:
      context: .
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
    container_name: celery_app
    environment:
      CELERY_BROKER_URL: 'redis://redis:5370'
      CELERY_RESULT_BACKEND: 'redis://redis:5370'
    command: ["/fastapi_app/docker/celery.sh", "celery"]
    depends_on:
      - redis





#docker compose build
#docker compose up